name: Terraform CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      - run: terraform fmt -check -recursive
      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: environments/dev
      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/dev

  plan:
    if: github.event_name == 'pull_request'
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::938835673448:role/github-actions-role
          aws-region: eu-west-1
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev
      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: environments/dev
